services:
  frontend:
    build: .
    container_name: gen-frontend
    ports:
      - "3333:3333"
    command: >
      bash -c "npm install && ng serve --host 0.0.0.0 --port 3333"
    networks:
      - gen-network

networks:
  gen-network:
    driver: bridge
